def help():
    print("Usage:")
    print("   gpost [command] [wordlist] [url]")
    print("")
    print("command:")
    print("   dir         Uses directory")
    print("   dns         Uses subdomain")
    print("   -h          help for gpost")
    print("   --help      help for gpost")
    print("")
    print("Exsample:")
    print("   gpost dir 'gpost/main/word_list.txt' 'https://github.com/'")
    print("")
    print("+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*")
